parameters:
    nvbooster_sortingmanager.class: nvbooster\SortingManager\SortingManager
    nvbooster_sortingmanager.twigextension.class: nvbooster\SortingManagerBundle\Twig\SortableColumnExtension

services:
    nvbooster_sortingmanager:
        class: "%nvbooster_sortingmanager.class%"
        public: true
    nvbooster_sortingmanager.twigextension.class:
        class: "%nvbooster_sortingmanager.twigextension.class%"
        arguments: ["@request_stack", "@?translator"]
        tags:
            - { name: twig.extension }
