parameters:
    nvbooster_sortingmanager_storage.cookie.class: nvbooster\SortingManagerBundle\ConfigStorage\CookieStorage
    nvbooster_sortingmanager.cookie_save_listener.class: nvbooster\SortingManagerBundle\EventListener\SaveSortingCookieListener

services:
    nvbooster_sortingmanager_storage.cookie:
        class: "%nvbooster_sortingmanager_storage.cookie.class%"
        arguments: ["@request_stack"]
        public: false

    nvbooster_sortingmanager.cookie_save_listener:
        class: "%nvbooster_sortingmanager.cookie_save_listener.class%"
        arguments: ["@nvbooster_sortingmanager_storage.cookie", null]
        tags:
            - { name: "kernel.event_subscriber" }